### ISSUE TITLE
What Data types should we consider

### ISSUE THREAD

**Issue by Clare-Joyce** [Clare-Joyce/CDS_Project#6]
I have set the insert function to add "any" element meaning any type of data is accepted, this might be problematic if someone trying to use it with objects different fro the usual string, int, float objects. Something to discuss.

**Comment by Sarigakakkamani** [comment]
As per the instruction document it says to test natural words , random strings or DNA. which is asking to test at least two data types. I think even though it says two data types, It is basically referring to strings, so may be we can go ahead with strings and testing for two completely different formats.

**Comment by Clare-Joyce** [comment]
Okay, we will use strings then. Thanks!
